# This is a basic workflow that is manually triggered

name: Delpoy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    # Inputs the workflow accepts.
    branches:
      - 'main'
      - 'releases/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy:
    # The type of runner that the job will run on
    runs-on: self-hosted


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v1 
    # Runs a single command using the runners shell
    - run: |
        cp index.html /Users/maulana/Data/Playground/demo-lukan
